### ISSUE TITLE
Error while creating the environment

### ISSUE THREAD

**Issue by IlariaSartoriGH** [fonnesbeck/bayes_course_june_2024#3]
### Discussed in https://github.com/fonnesbeck/bayes_course_june_2024/discussions/2

<div type='discussions-op-text'>

<sup>Originally posted by **IlariaSartoriGH** June 11, 2024</sup>
I am facing a strange error when installing the environment using conda.

When I run `conda env create`
I get
`PermissionError: [Errno 13] Permission denied: '/Users/{My_user_name}/anaconda3/pkgs/cache/29e82f7e.info.json'`

I am on a Mac and I am using these versions:
  conda version : 24.5.0
  conda-build version : 24.1.2
  python version : 3.11.7.final.0

Does anyone know what could be causing this?</div>

**Comment by fonnesbeck** [comment]
It looks like a permissions issue with your anaconda directory. You can try changing it to something like:

`chmod a+w ~/anaconda3`

Or you can try re-installing anaconda (or even  better, mambaforge as in the instructions on the README)

**Comment by IlariaSartoriGH** [comment]
Thanks a lot @fonnesbeck ! Actually it seems that the problem somehow solved itself and I was able to install the environment after switching on and off the computer. All good now
